// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dgwchcikhlapeqqvfrnh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnd2NoY2lraGxhcGVxcXZmcm5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNzU0NTQsImV4cCI6MjA3MTk1MTQ1NH0.-D26lxv7JOw2PqsBBLFtybD3RKR5QUNzsscwBZT6Qt4";

// Import the supabase client like this:
// import { supabase } from "@/infrastructure/api/supabase";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
